name: Build Android APK
on:
  push:
    branches: [ 'main', 'master' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build APK
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
      run: |
        chmod +x gradlew
        ./gradlew :app:assembleDebug --stacktrace --no-daemon
        ls -la
        find . -name "*.apk"
    - uses: actions/upload-artifact@v4
      with:
        name: Ibkar-App
        path: '**/*.apk'
        if-no-files-found: error
